// <auto-generated />
// Generated by chat/tools/model-hashes/fetch_chat_model_hashes.py on 2026-09-11.
// DO NOT EDIT BY HAND. These are the two presets' genai_config.json bodies EXACTLY as published at
// the pinned revisions - the same bytes ChatPresets.g.cs pins for provisioning. The digests below
// are asserted by a tier-1 test (plan adjustment 24), so a hand-edit that "tidies" the JSON turns
// every section 16.1 shape assertion loud instead of silently wrong.

namespace Qavren.Edge.Chat.Tests.Fixtures;

internal static class GenAiConfigFixtures
{
    /// <summary>Arm/llama-3-2-1b-instruct-onnx-genai-int4-kquantlast-emb-int8-vivo-x300 at 333c515af8b9355011c0b295c4356c9c24b463ff.</summary>
    public const string LlamaConfigJson = """
{
    "model": {
        "bos_token_id": 128000,
        "context_length": 4096,
        "decoder": {
            "session_options": {
                "log_id": "onnxruntime-genai",
                "provider_options": []
            },
            "filename": "model.onnx",
            "head_size": 64,
            "hidden_size": 2048,
            "inputs": {
                "input_ids": "input_ids",
                "attention_mask": "attention_mask",
                "past_key_names": "past_key_values.%d.key",
                "past_value_names": "past_key_values.%d.value"
            },
            "outputs": {
                "logits": "logits",
                "present_key_names": "present.%d.key",
                "present_value_names": "present.%d.value"
            },
            "num_attention_heads": 32,
            "num_hidden_layers": 16,
            "num_key_value_heads": 8
        },
        "eos_token_id": [
            128001,
            128008,
            128009
        ],
        "pad_token_id": 128001,
        "type": "llama",
        "vocab_size": 128256
    },
    "search": {
        "diversity_penalty": 0.0,
        "do_sample": true,
        "early_stopping": true,
        "length_penalty": 1.0,
        "max_length": 4096,
        "min_length": 0,
        "no_repeat_ngram_size": 0,
        "num_beams": 1,
        "num_return_sequences": 1,
        "past_present_share_buffer": true,
        "repetition_penalty": 1.0,
        "temperature": 0.6,
        "top_k": 50,
        "top_p": 0.9
    }
}
""";
    public const string LlamaConfigSha256 = "359d47db9f4e3626bd51a4b5ccf839489dfbe099e46e039dc63c0ca0118f4f1c";
    public const int LlamaConfigLength = 1_536;

    /// <summary>Arm/qwen3-0-6b-onnx-genai-int4-kquantlast-emb-int4 at c1d7bbbbb20630eef24c00d8ad18250bd57b232c.</summary>
    public const string QwenConfigJson = """
{
    "model": {
        "bos_token_id": 151643,
        "context_length": 40960,
        "decoder": {
            "session_options": {
                "log_id": "onnxruntime-genai",
                "provider_options": []
            },
            "filename": "model.onnx",
            "head_size": 128,
            "hidden_size": 1024,
            "inputs": {
                "input_ids": "input_ids",
                "attention_mask": "attention_mask",
                "past_key_names": "past_key_values.%d.key",
                "past_value_names": "past_key_values.%d.value"
            },
            "outputs": {
                "logits": "logits",
                "present_key_names": "present.%d.key",
                "present_value_names": "present.%d.value"
            },
            "num_attention_heads": 16,
            "num_hidden_layers": 28,
            "num_key_value_heads": 8
        },
        "eos_token_id": [
            151645,
            151643
        ],
        "pad_token_id": 151643,
        "type": "qwen3",
        "vocab_size": 151936
    },
    "search": {
        "diversity_penalty": 0.0,
        "do_sample": true,
        "early_stopping": true,
        "length_penalty": 1.0,
        "max_length": 40960,
        "min_length": 0,
        "no_repeat_ngram_size": 0,
        "num_beams": 1,
        "num_return_sequences": 1,
        "past_present_share_buffer": true,
        "repetition_penalty": 1.0,
        "temperature": 0.6,
        "top_k": 20,
        "top_p": 0.95
    }
}
""";
    public const string QwenConfigSha256 = "67348085a5b994a6b6d94e56e395e675d8ef4732c3c46ff75de30a541489fd3f";
    public const int QwenConfigLength = 1_520;
}
