using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Qavren.Edge.ProviderGen;

internal static class ManifestBuilder
{
    /// <summary>
    /// Fully qualified CLR type name without assembly qualification. <see cref="Type.FullName"/>
    /// renders a constructed generic's arguments assembly-qualified
    /// ("System.ReadOnlySpan`1[[System.Byte, System.Private.CoreLib, Version=...]]"), which would bake
    /// the running runtime's version into the manifest. This renders "System.ReadOnlySpan`1[System.Byte]".
    /// </summary>
    internal static string FormatType(Type t)
    {
        if (t.IsByRef)
        {
            return FormatType(t.GetElementType()!) + "&";
        }

        if (t.IsPointer)
        {
            return FormatType(t.GetElementType()!) + "*";
        }

        if (t.IsArray)
        {
            return FormatType(t.GetElementType()!) + "[" + new string(',', t.GetArrayRank() - 1) + "]";
        }

        if (t.IsConstructedGenericType)
        {
            var args = string.Join(",", t.GetGenericArguments().Select(FormatType));
            return t.GetGenericTypeDefinition().FullName + "[" + args + "]";
        }

        return t.FullName ?? t.Name;
    }

    /// <summary>"ReturnType Name(ParamType name, ...)" using fully qualified CLR type names.</summary>
    internal static string FormatMember(MethodInfo m)
    {
        var sb = new StringBuilder();
        sb.Append(FormatType(m.ReturnType)).Append(' ').Append(m.Name).Append('(');
        var ps = m.GetParameters();
        for (var i = 0; i < ps.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(FormatType(ps[i].ParameterType)).Append(' ').Append(ps[i].Name);
        }

        return sb.Append(')').ToString();
    }

    internal static JsonObject Build()
    {
        var iface = typeof(SQLitePCL.ISQLite3Provider);
        var core = iface.Assembly.GetName();

        var members = iface.GetMethods(BindingFlags.Public | BindingFlags.Instance)
            .Select(FormatMember)
            .OrderBy(s => s, StringComparer.Ordinal)
            .ToArray();

        var missing = SpotCheck.ExpectedSignatures
            .Where(expected => !members.Contains(expected, StringComparer.Ordinal))
            .ToArray();

        if (missing.Length > 0)
        {
            throw new InvalidOperationException(
                "ISQLite3Provider no longer matches the transcribed v3.0.5 surface. Missing:" +
                Environment.NewLine + "  " + string.Join(Environment.NewLine + "  ", missing));
        }

        var manifest = new JsonObject
        {
            ["$comment"] =
                "GENERATED by 'providergen manifest'. Do not hand-edit. " +
                "Members are reflected from SQLitePCL.ISQLite3Provider and validated against the " +
                "verbatim v3.0.5 signatures in SpotCheck.cs.",
            ["sqlitePclRawCoreVersion"] = core.Version?.ToString(),
            ["providerClassName"] = "SQLite3Provider_qedge",
            ["providerNamespace"] = "Qavren.Edge.Sqlite.Provider",
            ["defaultReportedLibraryName"] = "qedge_sqlite3",
            ["libraryNameByTargetFramework"] = new JsonObject
            {
                ["net10.0"] = "qedge_sqlite3",
                ["net10.0-ios"] = "__Internal",
                ["net10.0-maccatalyst"] = "qedge_sqlite3",
                ["net10.0-android"] = "qedge_sqlite3",
                ["net10.0-windows"] = "qedge_sqlite3",
            },
            ["memberCount"] = members.Length,
            ["members"] = new JsonArray([.. members.Select(m => (JsonNode)JsonValue.Create(m)!)]),
        };

        return manifest;
    }

    internal static string Serialize(JsonObject manifest)
        => manifest.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine;
}
