using System.Text.Json.Nodes;

namespace Qavren.Edge.ProviderGen;

internal static class ProviderRenderer
{
    /// <summary>
    /// The template is upstream's Apache-2.0 licensed generated provider
    /// (SQLitePCLRaw.provider.internal/Generated/provider_internal_funcptrs.cs at tag v3.0.5),
    /// vendored under foundation/src/Qavren.Edge.Sqlite.Provider/Template/. Substitutions are
    /// mechanical string replacements so the diff against upstream stays reviewable.
    /// </summary>
    internal static string Render(string template, JsonObject manifest)
    {
        var className = (string)manifest["providerClassName"]!;
        var ns = (string)manifest["providerNamespace"]!;

        var rendered = template
            .Replace("namespace SQLitePCL", "namespace " + ns, StringComparison.Ordinal)
            .Replace("SQLite3Provider_internal", className, StringComparison.Ordinal)
            // net10.0-ios implicitly imports Foundation, which also defines PreserveAttribute.
            // Inside namespace SQLitePCL upstream wins by proximity; after the rename it is
            // ambiguous (CS0104), so the single attribute usage is qualified.
            .Replace("[Preserve(AllMembers = true)]",
                     "[SQLitePCL.Preserve(AllMembers = true)]",
                     StringComparison.Ordinal)
            .Replace("private const string SQLITE_DLL = \"__Internal\";",
                     "private const string SQLITE_DLL = QedgeNativeLibrary.DllImportName;",
                     StringComparison.Ordinal)
            .Replace("string ISQLite3Provider.GetNativeLibraryName()\n        {\n            return \"__Internal\";\n        }",
                     "string ISQLite3Provider.GetNativeLibraryName()\n        {\n            return QedgeNativeLibrary.ReportedName;\n        }",
                     StringComparison.Ordinal);

        if (rendered.Contains("__Internal", StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "Template still contains '__Internal' after substitution; the upstream file shape changed.");
        }

        // The template body lives in namespace SQLitePCL and references its neighbours
        // (ISQLite3Provider, Preserve, utf8z, sqlite3, sqlite3_stmt, hook_handle, ...) unqualified.
        // Renaming the namespace orphans every one of them, so the emitted file imports the
        // original namespace at compilation-unit level. Nothing in the body is reformatted.
        return "// <auto-generated>" + Environment.NewLine +
               "// Generated by foundation/tools/ProviderGen. Do not edit." + Environment.NewLine +
               "// Derived from ericsink/SQLitePCL.raw v3.0.5, Apache-2.0. See THIRD-PARTY-NOTICES.md." + Environment.NewLine +
               "// </auto-generated>" + Environment.NewLine +
               "using SQLitePCL;" + Environment.NewLine +
               Environment.NewLine +
               rendered;
    }
}
