using System.Text.Json.Nodes;

namespace Qavren.Edge.ProviderGen;

internal static class ProviderRenderer
{
    /// <summary>
    /// The template is upstream's Apache-2.0 licensed generated provider
    /// (SQLitePCLRaw.provider.internal/Generated/provider_internal_funcptrs.cs at tag v3.0.5),
    /// vendored under foundation/src/Qavren.Edge.Sqlite.Provider/Template/. Substitutions are
    /// mechanical string replacements so the diff against upstream stays reviewable.
    /// </summary>
    internal static string Render(string template, JsonObject manifest)
    {
        var className = (string)manifest["providerClassName"]!;
        var ns = (string)manifest["providerNamespace"]!;

        var rendered = template
            .Replace("namespace SQLitePCL", "namespace " + ns, StringComparison.Ordinal)
            .Replace("SQLite3Provider_internal", className, StringComparison.Ordinal)
            .Replace("private const string SQLITE_DLL = \"__Internal\";",
                     "private const string SQLITE_DLL = QedgeNativeLibrary.DllImportName;",
                     StringComparison.Ordinal)
            .Replace("string ISQLite3Provider.GetNativeLibraryName()\n\t\t{\n\t\t\treturn \"__Internal\";\n\t\t}",
                     "string ISQLite3Provider.GetNativeLibraryName()\n\t\t{\n\t\t\treturn QedgeNativeLibrary.ReportedName;\n\t\t}",
                     StringComparison.Ordinal);

        if (rendered.Contains("__Internal", StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "Template still contains '__Internal' after substitution; the upstream file shape changed.");
        }

        return "// <auto-generated>" + Environment.NewLine +
               "// Generated by foundation/tools/ProviderGen. Do not edit." + Environment.NewLine +
               "// Derived from ericsink/SQLitePCL.raw v3.0.5, Apache-2.0. See THIRD-PARTY-NOTICES.md." + Environment.NewLine +
               "// </auto-generated>" + Environment.NewLine +
               rendered;
    }
}
