// <auto-generated>
// Regenerate with embeddings/tools/model-hashes/fetch_preset_hashes.py.
// NEVER a build step. Every SHA-256 below is the git-LFS oid for an LFS-backed file and
// a locally computed digest for a plain git blob -- see the script's docstring.
// </auto-generated>

using Qavren.Edge.Onnx;

namespace Qavren.Edge.Embeddings.Onnx;

/// <summary>The pinned manifests behind <c>EmbeddingPresets</c>.</summary>
internal static class EmbeddingPresetManifests
{
    public static readonly OnnxModelManifest MiniLmL6V2Int8 = new()
    {
        ModelId = "all-minilm-l6-v2-int8",
        GraphFile = "onnx/model_qint8_arm64.onnx",
        SpdxLicense = "Apache-2.0",
        HuggingFaceRepo = "sentence-transformers/all-MiniLM-L6-v2",
        HuggingFaceRevision = "1110a243fdf4706b3f48f1d95db1a4f5529b4d41",
        Files =
        [
            new("onnx/model_qint8_arm64.onnx", OnnxModelFileRole.Graph, 23026053, "4278337fd0ff3c68bfb6291042cad8ab363e1d9fbc43dcb499fe91c871902474"),
            new("vocab.txt", OnnxModelFileRole.Vocabulary, 231508, "07eced375cec144d27c900241f3e339478dec958f92fddbc551f295c992038a3"),
        ],
    };

    public static readonly OnnxModelManifest MiniLmL6V2Fp32 = new()
    {
        ModelId = "all-minilm-l6-v2-fp32",
        GraphFile = "onnx/model.onnx",
        SpdxLicense = "Apache-2.0",
        HuggingFaceRepo = "sentence-transformers/all-MiniLM-L6-v2",
        HuggingFaceRevision = "1110a243fdf4706b3f48f1d95db1a4f5529b4d41",
        Files =
        [
            new("onnx/model.onnx", OnnxModelFileRole.Graph, 90405214, "6fd5d72fe4589f189f8ebc006442dbb529bb7ce38f8082112682524616046452"),
            new("vocab.txt", OnnxModelFileRole.Vocabulary, 231508, "07eced375cec144d27c900241f3e339478dec958f92fddbc551f295c992038a3"),
        ],
    };

    public static readonly OnnxModelManifest BgeSmallEnV15 = new()
    {
        ModelId = "bge-small-en-v1.5",
        GraphFile = "onnx/model.onnx",
        SpdxLicense = "MIT",
        HuggingFaceRepo = "BAAI/bge-small-en-v1.5",
        HuggingFaceRevision = "5c38ec7c405ec4b44b94cc5a9bb96e735b38267a",
        Files =
        [
            new("onnx/model.onnx", OnnxModelFileRole.Graph, 133093490, "828e1496d7fabb79cfa4dcd84fa38625c0d3d21da474a00f08db0f559940cf35"),
            new("vocab.txt", OnnxModelFileRole.Vocabulary, 231508, "07eced375cec144d27c900241f3e339478dec958f92fddbc551f295c992038a3"),
        ],
    };

    public static readonly OnnxModelManifest NomicEmbedTextV15Int8 = new()
    {
        ModelId = "nomic-embed-text-v1.5-int8",
        GraphFile = "onnx/model_quantized.onnx",
        SpdxLicense = "Apache-2.0",
        HuggingFaceRepo = "nomic-ai/nomic-embed-text-v1.5",
        HuggingFaceRevision = "e9b6763023c676ca8431644204f50c2b100d9aab",
        Files =
        [
            new("onnx/model_quantized.onnx", OnnxModelFileRole.Graph, 137296292, "b4342336debaea79de872370664b0aaeb67dea4605513d00ee236ea871a81f27"),
            new("vocab.txt", OnnxModelFileRole.Vocabulary, 231508, "07eced375cec144d27c900241f3e339478dec958f92fddbc551f295c992038a3"),
        ],
    };

}
