using Qavren.Edge.Onnx;

namespace Qavren.Edge.Chat;

/// <summary>One ready-made ORT GenAI model folder: its manifest, its geometry, its defaults.</summary>
public sealed record ChatPreset
{
    /// <summary>The id <c>AddOnnxChat</c> and <see cref="ChatPresets.ById"/> use.</summary>
    public required string Id { get; init; }

    /// <summary>
    /// Sub-project 2's manifest, unchanged. <c>GraphFile</c> names the decoder <c>.onnx</c>, so
    /// the content-addressed directory is keyed on the weights. <c>genai_config.json</c>,
    /// <c>tokenizer.json</c>, <c>tokenizer_config.json</c> and <c>chat_template.jinja</c> ride as
    /// <c>Auxiliary</c>; <c>model.onnx.data</c> rides as <c>GraphExternalData</c>.
    /// </summary>
    public required OnnxModelManifest Manifest { get; init; }

    /// <summary>The decoder geometry the memory budget is computed from, before anything is mapped.</summary>
    public required ChatModelShape Shape { get; init; }

    /// <summary>The manifest-relative name of the GenAI configuration file.</summary>
    public string GenAiConfigFile { get; init; } = "genai_config.json";

    /// <summary>What an about screen or a consent sheet shows.</summary>
    public required string DisplayName { get; init; }

    /// <summary>
    /// The licence URL an about screen needs; <c>Manifest.SpdxLicense</c> carries the identifier.
    /// <para>
    /// <b>Not every chat model's licence has an SPDX identifier, and the field must not pretend
    /// otherwise.</b> Sub-project 2 documents <c>SpdxLicense</c> as "the SPDX identifier of the
    /// model's licence, for an about screen", and the consent sheet and the repo's
    /// <c>THIRD-PARTY-NOTICES.md</c> both surface that string verbatim. The Llama 3.2 Community
    /// Licence is not on the SPDX list, so it takes SPDX's own convention for a licence that is
    /// not: <c>LicenseRef-LLAMA-3.2-Community</c>, never a bare <c>LLAMA-3.2-Community</c>, which
    /// is not a valid SPDX expression at all. <c>Qwen3_600MInt4</c> is <c>Apache-2.0</c>, a real
    /// identifier. The field therefore holds an SPDX <i>expression</i>, of which a
    /// <c>LicenseRef-</c> value is a legal one, and the generator script emits that spelling.
    /// </para>
    /// </summary>
    public Uri? LicenseUri { get; init; }

    /// <summary>Matched against the accumulated decoded text, never against one decoded token.</summary>
    public IReadOnlyList<string> StopSequences { get; init; } = [];

    /// <summary>Never above <see cref="ChatModelShape.ContextLength"/>.</summary>
    public int DefaultMaxContextTokens { get; init; } = 4096;

    /// <summary>The per-turn output cap when nothing nearer the call site sets one.</summary>
    public int DefaultMaxOutputTokens { get; init; } = 512;

    /// <summary>The sampling temperature when nothing nearer the call site sets one.</summary>
    public float DefaultTemperature { get; init; } = 0.7f;

    /// <summary>The nucleus cut-off when nothing nearer the call site sets one.</summary>
    public float DefaultTopP { get; init; } = 0.9f;

    /// <summary>The top-k cut-off when nothing nearer the call site sets one.</summary>
    public int DefaultTopK { get; init; } = 50;
}

/// <summary>
/// The shipped catalogue, generated by <c>chat/tools/model-hashes/fetch_chat_model_hashes.py</c>
/// into <c>ChatPresets.g.cs</c> with literal SHA-256s and a pinned commit revision, exactly as
/// sub-project 2's <c>EmbeddingPresets.g.cs</c> is. The script reads each repo's own
/// <c>genai_config.json</c> and emits the <see cref="ChatModelShape"/> from it, so no geometry
/// value in this catalogue is hand-typed.
/// <para>
/// <b>There is deliberately no default preset.</b> The two entries carry different licences, and a
/// silently-chosen 1.24 GB download under the Llama 3.2 Community Licence is not a default anyone
/// should inherit. <c>AddOnnxChat</c> takes a preset as a required argument.
/// </para>
/// <para>
/// <b>Each preset's sampling defaults are the model's own shipped <c>search</c> values, not this
/// type's defaults</b> (plan adjustment 15): Llama ships 0.6 / 0.9 / 50 and Qwen ships
/// 0.6 / 0.95 / 20, and a preset that silently sampled differently from the publisher's own
/// <c>genai_config.json</c> would be a quality regression nobody would attribute. <see cref="ChatPreset"/>'s
/// own defaults stay as declared, for a preset somebody writes by hand.
/// </para>
/// </summary>
public static partial class ChatPresets
{
    /// <summary>Every shipped preset, in catalogue order.</summary>
    public static IReadOnlyList<ChatPreset> All => AllPresets;

    /// <summary>Looks a preset up by <see cref="ChatPreset.Id"/>.</summary>
    /// <param name="id">The preset id, compared ordinally.</param>
    /// <returns>The preset.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="id"/> is null.</exception>
    /// <exception cref="EdgeChatException"><see cref="EdgeErrorCode.ChatModelNotRegistered"/> (7003).</exception>
    public static ChatPreset ById(string id)
    {
        ArgumentNullException.ThrowIfNull(id);

        foreach (var preset in AllPresets)
        {
            if (string.Equals(preset.Id, id, StringComparison.Ordinal))
            {
                return preset;
            }
        }

        var known = string.Join(", ", AllPresets.Select(static p => p.Id));

        throw new EdgeChatException(
            EdgeErrorCode.ChatModelNotRegistered,
            $"No chat preset is registered as '{id}'. The shipped catalogue holds: {known}.")
        {
            PresetId = id,
            Remediation =
                "Pass one of the catalogue's ids, or construct a ChatPreset of your own and hand " +
                "it to AddOnnxChat - the catalogue is a convenience, not the registry.",
        };
    }
}
