// <auto-generated />
// Generated by chat/tools/model-hashes/fetch_chat_model_hashes.py on 2026-09-11.
// DO NOT EDIT BY HAND. Re-run the script and commit the diff; a changed digest is a deliberate
// decision about which weights ship, never a merge conflict to resolve.
//
// Every geometry value below is read from the repo's own genai_config.json at the pinned commit,
// and every digest is the git-LFS oid where the file is LFS-backed and a downloaded-and-hashed
// SHA-256 where it is not. No value here is hand-typed.

using Qavren.Edge.Onnx;

namespace Qavren.Edge.Chat;

public static partial class ChatPresets
{
    /// <summary>
    /// <c>Arm/llama-3-2-1b-instruct-onnx-genai-int4-kquantlast-emb-int8-vivo-x300</c>.
    /// 1.241 GB decimal on disk across six files; 1167.52 MiB of resident weights; context 4096 as
    /// shipped (the publisher patched it down from Llama's stock 131072 so the KV cache fits a
    /// phone). Geometry: 16 layers, 8 KV heads, head size 64, vocab 128256 - <b>32 KiB of KV per
    /// token</b>. Measured on a vivo X300 (Android 16, ORT 1.27.0 CPU EP, 4 threads): 30.564 tok/s
    /// decode, TTFT 950 ms, peak RSS 1280 MiB, model load 1.61 s, MMLU 5-shot 44.2%.
    /// <b>No iOS figure exists for this or any other ORT GenAI model.</b>
    /// </summary>
    public static ChatPreset Llama32_1BInstructInt4 { get; } = new()
    {
        Id = "llama-3.2-1b-instruct-int4",
        DisplayName = "Llama 3.2 1B Instruct (int4)",
        LicenseUri = new Uri("https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/blob/main/LICENSE.txt"),
        Manifest = new OnnxModelManifest
        {
            ModelId = "llama-3.2-1b-instruct-int4",
            GraphFile = "model.onnx",
            SpdxLicense = "LicenseRef-LLAMA-3.2-Community",
            HuggingFaceRepo = "Arm/llama-3-2-1b-instruct-onnx-genai-int4-kquantlast-emb-int8-vivo-x300",
            HuggingFaceRevision = "333c515af8b9355011c0b295c4356c9c24b463ff",
            Files =
            [
                new OnnxModelFile("model.onnx", OnnxModelFileRole.Graph, 141_626,
                    "742f2292f396bbc65a511c361e37e1b1bcef40ebb38003aab38461549e7493a4"),
                new OnnxModelFile("model.onnx.data", OnnxModelFileRole.GraphExternalData, 1_224_094_720,
                    "ab128a60ea1be913b37f91ab305c059cf36b88383d7e9b907bfcaf0460b859bd"),
                new OnnxModelFile("genai_config.json", OnnxModelFileRole.Auxiliary, 1_536,
                    "359d47db9f4e3626bd51a4b5ccf839489dfbe099e46e039dc63c0ca0118f4f1c"),
                new OnnxModelFile("tokenizer.json", OnnxModelFileRole.Auxiliary, 17_209_920,
                    "6b9e4e7fb171f92fd137b777cc2714bf87d11576700a1dcd7a399e7bbe39537b"),
                new OnnxModelFile("tokenizer_config.json", OnnxModelFileRole.Auxiliary, 353,
                    "502d3a27e52540463d85a947099459fb0f8aea88dd1cf9889368576de89dd668"),
                new OnnxModelFile("chat_template.jinja", OnnxModelFileRole.Auxiliary, 3_827,
                    "5816fce10444e03c2e9ee1ef8a4a1ea61ae7e69e438613f3b17b69d0426223a4"),
            ],
        },
        Shape = new ChatModelShape
        {
            ModelType = "llama",
            ContextLength = 4096,
            VocabSize = 128_256,
            NumHiddenLayers = 16,
            NumKeyValueHeads = 8,
            HeadSize = 64,
            SlidingWindow = null,
            DecoderFileName = "model.onnx",
            WeightsBytes = 1_224_236_346L,
            MeasuredPeakBytes = 1_342_177_280L,   // 1280 MiB
            MeasuredOn = "vivo X300, Android 16, ORT 1.27.0 CPU EP, 4 threads",
        },
        StopSequences = ["<|eot_id|>", "<|eom_id|>", "<|end_of_text|>"],
        DefaultMaxContextTokens = 4096,
        DefaultMaxOutputTokens = 512,
        DefaultTemperature = 0.6f,
        DefaultTopP = 0.9f,
        DefaultTopK = 50,
    };

    /// <summary>
    /// <c>Arm/qwen3-0-6b-onnx-genai-int4-kquantlast-emb-int4</c>. 495 MB decimal on disk across six
    /// files; 461.25 MiB of resident weights; Apache-2.0 - the preset for an app that cannot take
    /// the Llama terms, and the model the nightly lane uses.
    /// <para>
    /// <b>Smaller on disk is not smaller in memory, and here are the numbers.</b> 28 layers, 8 KV
    /// heads, head size 128 - <b>112 KiB of KV per token</b>, 3.5x this catalogue's larger preset,
    /// against a third of the weights. At 4096 tokens its KV cache alone is 448 MiB. Its declared
    /// <c>context_length</c> is <b>40960</b>, so a generator built with no <c>max_length</c> would
    /// allocate <b>4480 MiB</b> of KV cache - which is exactly the jetsam scenario the memory budget
    /// and the belt-and-braces <c>search.max_length</c> exist to prevent.
    /// </para>
    /// <para>
    /// Its only published throughput is AWS Graviton (70.4 tok/s, peak 838 MB decimal), and that
    /// figure is deliberately <b>not</b> in <c>MeasuredPeakBytes</c>: the budget reads that field
    /// alone and has no way to discount a measurement by where it was taken, so a server peak
    /// entering it would silently become a phone budget.
    /// </para>
    /// </summary>
    public static ChatPreset Qwen3_600MInt4 { get; } = new()
    {
        Id = "qwen3-0.6b-int4",
        DisplayName = "Qwen3 0.6B (int4)",
        LicenseUri = new Uri("https://www.apache.org/licenses/LICENSE-2.0"),
        Manifest = new OnnxModelManifest
        {
            ModelId = "qwen3-0.6b-int4",
            GraphFile = "model.onnx",
            SpdxLicense = "Apache-2.0",
            HuggingFaceRepo = "Arm/qwen3-0-6b-onnx-genai-int4-kquantlast-emb-int4",
            HuggingFaceRevision = "c1d7bbbbb20630eef24c00d8ad18250bd57b232c",
            Files =
            [
                new OnnxModelFile("model.onnx", OnnxModelFileRole.Graph, 331_869,
                    "e9208ab7164ea6da0206eec2a2f0996a24e75d164f85823b02111f23046aab89"),
                new OnnxModelFile("model.onnx.data", OnnxModelFileRole.GraphExternalData, 483_328_000,
                    "52640ca0d65e00d33dfb10b822c6a41e31bab1aaa6a49457b1dc5952c0dab0fb"),
                new OnnxModelFile("genai_config.json", OnnxModelFileRole.Auxiliary, 1_520,
                    "67348085a5b994a6b6d94e56e395e675d8ef4732c3c46ff75de30a541489fd3f"),
                new OnnxModelFile("tokenizer.json", OnnxModelFileRole.Auxiliary, 11_422_650,
                    "be75606093db2094d7cd20f3c2f385c212750648bd6ea4fb2bf507a6a4c55506"),
                new OnnxModelFile("tokenizer_config.json", OnnxModelFileRole.Auxiliary, 376,
                    "c56d783875898cebcf53c8797b61137efd52f1415be7531823b56f216f444527"),
                new OnnxModelFile("chat_template.jinja", OnnxModelFileRole.Auxiliary, 4_168,
                    "a55ee1b1660128b7098723e0abcd92caa0788061051c62d51cbe87d9cf1974d8"),
            ],
        },
        Shape = new ChatModelShape
        {
            ModelType = "qwen3",
            ContextLength = 40_960,
            VocabSize = 151_936,
            NumHiddenLayers = 28,
            NumKeyValueHeads = 8,
            HeadSize = 128,
            SlidingWindow = null,
            DecoderFileName = "model.onnx",
            WeightsBytes = 483_659_869L,
            MeasuredPeakBytes = null,
            MeasuredOn = "AWS Graviton g4 (published 70.4 tok/s, peak 838 MB decimal) - a server "
                       + "measurement, recorded here and deliberately NOT in MeasuredPeakBytes",
        },
        StopSequences = ["<|im_end|>", "<|endoftext|>"],
        DefaultMaxContextTokens = 4096,
        DefaultMaxOutputTokens = 512,
        DefaultTemperature = 0.6f,
        DefaultTopP = 0.95f,
        DefaultTopK = 20,
    };

    private static readonly ChatPreset[] AllPresets = [Llama32_1BInstructInt4, Qwen3_600MInt4];
}
